import os
from openai import OpenAI
import logging
from dotenv import load_dotenv
logger = logging.getLogger(__name__)
load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY environment variable is not set")

client = OpenAI(
    api_key=api_key,
    base_url="https://openrouter.ai/api/v1"  
)

SYSTEM_PROMPT = """
You are an expert Senior AML (Anti-Money Laundering) Investigator. 
You are reviewing an alert generated by our machine learning system.
Based ONLY on the evidence provided below, write a 2-3 sentence investigative summary for a junior analyst.
Do not make up facts. Do not assume crimes that aren't supported by the data.
Just synthesize the provided evidence into a clear, professional narrative.
Mention specific red flags like structuring, smurfing, high-risk corridors, or velocity if the data supports it.
"""

def generate_investigation_summary(translated_shap_context: str) -> str:
    """
    Sends translated SHAP evidence to LLM and returns the narrative.
    """
    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-120b:free",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Alert Evidence:\n{translated_shap_context}"}
            ],
            temperature=0.2 
        )
        return response.choices[0].message.content
    except Exception as e:
        logger.error(f"LLM call failed: {e}")
        return "Error generating AI summary. Please review raw SHAP values manually."